# Generated by Django 3.2.7 on 2021-11-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporting_entity',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
    ]
