# Generated by Django 3.2.7 on 2021-12-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbonmap', '0002_reporting_entity_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting_entity_address',
            name='address_country',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='reporting_entity_address',
            name='address_locality',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reporting_entity_address',
            name='address_region',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reporting_entity_address',
            name='postal_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='reporting_entity_address',
            name='street_address',
            field=models.CharField(max_length=255),
        ),
    ]
