# Generated by Django 3.2.7 on 2022-01-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbonmap', '0003_auto_20211212_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('entity_id', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='reporting_entity',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reporting_entity',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
